clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  eslint:
    image: marcbachmann/eslint:4.19.0
    group: test

  publish:
    group: build
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token, npm_token]
